PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

SELECT (geof:boundary(?o1) AS ?ret) 
WHERE { 
	GRAPH <https://geosparql.isti.cnr.it/fuseki/seminar-openllet/clc> {
		?s1 <http://geo.linkedopendata.gr/corine/ontology#asWKT> ?o1
	} 
} 