PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

SELECT ?s1 ?s2
WHERE { 
	GRAPH <https://geosparql.isti.cnr.it/fuseki/seminar-openllet/lgd> {
		?s1 <http://linkedgeodata.org/ontology/asWKT> ?o1
	} 
	GRAPH <https://geosparql.isti.cnr.it/fuseki/seminar-openllet/gag> {
		?s2 <http://geo.linkedopendata.gr/gag/ontology/asWKT> ?o2
	} 
	FILTER(geof:sfCrosses(?o1, ?o2)).  
} 
